export const PRIMARY = {
  BUTTON: {
    DEFAULT: { COLOR: '#FFFFFF', BACKGROUD: '#6542F1' },
    HOVER: { COLOR: '#FFFFFF', BACKGROUD: '#9982F4' },
    PRESS: { COLOR: '#FFFFFF', BACKGROUD: '#4B31B0' },
    DISABLED: { COLOR: '#D0CDCD', BACKGROUD: '#EDEDED' },
  },
};

export const SECONDARY = {
  BUTTON: {
    DEFAULT: { COLOR: '#3A3A3A', BACKGROUD: '#DEDEDE' },
    HOVER: { COLOR: '#3A3A3A', BACKGROUD: '#F3F3F3' },
    PRESS: { COLOR: '#3A3A3A', BACKGROUD: '#B8B7B9' },
    DISABLED: { COLOR: '#D0CDCD', BACKGROUD: '#EDEDED' },
  },
};

export const TERTIARY = {
  BUTTON: {
    DEFAULT: { COLOR: '#6542F1', BACKGROUD: '#FFFFFF', BORDER: '#6542F1' },
    HOVER: { COLOR: '#9982F4', BACKGROUD: '#FFFFFF', BORDER: '#9982F4' },
    PRESS: { COLOR: '#4B31B0', BACKGROUD: '#F0EDFC', BORDER: '#4B31B0' },
    DISABLED: { COLOR: '#D0CDCD', BACKGROUD: '#F6F6F6', BORDER: '#EDEDED' },
  },
};
